services:
  frontend:
    build: docker/frontend
    volumes:
      - ./repositories/frontend:/var/www/project/frontend:cached
  backend:
    build: docker/backend
    volumes:
      - ./repositories/backend:/var/www/project/backend:cached
  gateway:
    image: nginx
    depends_on:
      - frontend
      - backend
    ports:
      - $NGINX_LISTEN:80
    volumes:
      - ./docker/gateway/nginx/conf.d:/etc/nginx/conf.d
      - ./docker/gateway/nginx/nginx.conf:/etc/nginx/nginx.conf
      - ./docker/gateway/nginx/proxy.conf:/etc/nginx/proxy.conf
