services:
  frontend:
    build: docker/frontend
    volumes:
      - ./repositories/frontend:/var/www/project/frontend:cached
    environment:
      - PORT_FRONTEND
  backend:
    build: docker/backend
    volumes:
      - ./repositories/backend:/var/www/project/backend:cached
  gateway:
    image: nginx
    depends_on:
      - frontend
      - backend
    ports:
      - $PORT_NGINX:80
    environment:
      - PORT_FRONTEND
    volumes:
      - ./docker/gateway/nginx/conf.d:/etc/nginx/templates
      - ./docker/gateway/nginx/nginx.conf:/etc/nginx/nginx.conf
      - ./docker/gateway/nginx/proxy.conf:/etc/nginx/proxy.conf
    networks:
      default:
        aliases:
          - project.localhost
