services:
  backend:
    build: docker/backend
    volumes:
      - ./repositories/backend:/var/www/project/backend:cached
  frontend:
    build: docker/frontend
    volumes:
      - ./repositories/frontend:/var/www/project/frontend:cached
    environment:
      - PORT=$PORT_FRONTEND
  gateway:
    image: nginx
    depends_on:
      - backend
      - frontend
    ports:
      - $PORT_NGINX:80
    env_file:
      - .env
    volumes:
      - ./docker/gateway/nginx/conf.d:/etc/nginx/templates
      - ./docker/gateway/nginx/nginx.conf:/etc/nginx/nginx.conf
      - ./docker/gateway/nginx/proxy.conf:/etc/nginx/proxy.conf
    networks:
      default:
        aliases:
          - $HOST
